import { PROJECT_STATUSES } from '@level-zero/domain';
import { index, pgEnum, pgTable, text, timestamp, uuid } from 'drizzle-orm/pg-core';

export const projectStatusEnum = pgEnum('project_status', PROJECT_STATUSES);

/**
 * A project owns everything else. Ids are generated by the domain layer
 * (`IdGenerator`), not by the database, so a record has an identity before it
 * is ever persisted.
 */
export const projects = pgTable(
  'projects',
  {
    id: uuid('id').primaryKey(),
    name: text('name').notNull(),
    description: text('description'),
    status: projectStatusEnum('status').notNull().default('active'),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
    archivedAt: timestamp('archived_at', { withTimezone: true }),
  },
  (table) => [index('projects_status_idx').on(table.status)],
);

export type ProjectRow = typeof projects.$inferSelect;
export type NewProjectRow = typeof projects.$inferInsert;
